### ISSUE TITLE
WelcomePage issues

### ISSUE THREAD

**Issue by OfficialTomJ** [OfficialTomJ/IoTBay#11]
-WelcomePage route not defined in App.js.
-"Go to start" button has no functionality.
-A few blank link in the menu bar. Can we make this a reuseable component with mobile burger menu functionality?

![5e3ad88058c16f2ee9e5de0a408958be](https://github.com/OfficialTomJ/IoTBay/assets/8527295/d8180629-a5af-4984-8d87-d14b70d8bd95)

**Comment by Adam2221114** [comment]
“WelcomePage route not defined in App.js.”
-- i will do this

“"Go to start" button has no functionality.” 
--I want to create a ProductPage here, which will display product information and purchases. -- This may be the content of subsequent work, so I did not connect to some other pages.

“A few blank link in the menu bar. Can we make this a reuseable component with mobile burger menu functionality?”
-- My idea is that for the menu, it is the classification of sensors, because I don’t quite understand the content of the question, “Create a sales platform”
This menu can be used as a category, maybe the name confuses you, but this is my idea.
If it can get better, fix it

**Comment by Adam2221114** [comment]
welcomePage，i think it is not home page

Because, just a welcome, nothing more, connecting to login, products, etc. is enough.
I want the user to see the product by clicking "Get to start" on the welcomePage when opening the web page. that is homePage/ProductPage

Rather than what the user immediately sees when opening the webpage is the product

**Comment by Adam2221114** [comment]
Reply to "A few blank link in the menu bar. Can we make this a reuseable component with mobile burger menu functionality?"
--Yes, you can, but create these navigation buttons, they should be connected to the user login

The logic should be that users can only view functions such as "shopping cart", "order", and "support" after logging in, so inserting these guide buttons in advance is not very meaningful.

If you wish to insert these, I can do that.

**Comment by OfficialTomJ** [comment]
Sure, these are only minor things and it isn't a problem. Placeholder elements are okay at this stage to demonstrate how the user flow should work. But in the future, all of these should become reusable components where more elements can be easily added at will. Please look into how props and creating components works in React so we can add these menu bars into multiple pages. We will need to have a separate "Components" folder for this to keep things organised.

Here are things to work on for future iterations:

Define WelcomePage route in App.js: Ensure that the WelcomePage route is properly defined in the App.js file so that it can be accessed when navigating through the application.

Add functionality to "Go to start" button: Develop the ProductPage to display product information and purchases. When a user clicks on the "Go to start" button on the WelcomePage, it should navigate them to the ProductPage.

Create a reusable menu component: Transform the menu bar into a reusable component with mobile burger menu functionality. This component should include links or buttons for navigation, such as categories or other relevant sections. Ensure that the menu component is flexible and can be easily integrated into different parts of the application.

Connect navigation buttons to user login: Implement logic in the navigation buttons to ensure that certain functions like "shopping cart," "order," and "support" are only accessible to logged-in users. If a user is not logged in, these buttons should either not be displayed or should redirect them to the login/signup page.

Consider user flow: Take into account the user flow and experience when designing the functionality and layout of the application. Ensure that the navigation and features are intuitive and user-friendly.
